server:
  port: 8080

blog:
  title: 'DevPub'
  subtitle: 'Рассказы разработчиков'
  phone: '+79226556015'
  email: 'mariknv86@gmail.com'
  copyright: 'Марат Калимуллин'
  copyrightFrom: '2021'

#global-settings:
globalSettings:
    -
      code: 'MULTIUSER_MODE'
      name: 'Многопользовательский режим'
      value: 'NO'
    -
      code: 'POST_PREMODERATION'
      name: 'Премодерация постов'
      value: 'YES'
    -
      code: 'STATISTICS_IS_PUBLIC'
      name: 'Показывать всем статистику блога'
      value: 'YES'

spring:
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: default

#  security:
#    basic:
#      enabled: false
#  management:
#    security:
#      enabled: false

#  mail:
#    host: host
#    port: 587
#    username: username
#    password: pwd
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.batch_size: 20
        criteria.literal_handling_mode: BIND
        show-sql: true
        format-sql: true
        use_sql_comments: true

  http:
    multipart:
      max-file-size: 5MB
      max-request-size: -1
      file-size-threshold: 100KB
      enabled: true
      location: ${java.io.tmpdir}

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useTimezone=true&serverTimezone=GMT&useSSL=false
    username: root
    password: testtest
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 7190000
      minimumIdle: 2
      maximumPoolSize: 50
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat #форматирование дат в ISO формате (требования фронта, иначе не работает Java 8 Date Api)
    serialization:
      FAIL_ON_EMPTY_BEANS: false #отсутствие свойств не приводит к ошибке
    default-property-inclusion: NON_NULL #не сериализовывать null поля

  flyway:
    check-location: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306
    schemas: BLOG
    user: "root"
    password: "testtest"